/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.generator;

import com.google.common.base.Objects;
import com.google.common.collect.Iterables;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.common.util.TreeIterator;
import org.eclipse.emf.common.util.URI;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.eclipse.xtext.xbase.lib.ExclusiveRange;
import org.eclipse.xtext.xbase.lib.IteratorExtensions;
import org.xtext.example.mydsl.myDsl.ABin;
import org.xtext.example.mydsl.myDsl.AccSucc;
import org.xtext.example.mydsl.myDsl.Affectation;
import org.xtext.example.mydsl.myDsl.COMPARATEUR;
import org.xtext.example.mydsl.myDsl.Commande;
import org.xtext.example.mydsl.myDsl.Commandes;
import org.xtext.example.mydsl.myDsl.Condition;
import org.xtext.example.mydsl.myDsl.ElemSimple;
import org.xtext.example.mydsl.myDsl.ExprSimple;
import org.xtext.example.mydsl.myDsl.Expression;
import org.xtext.example.mydsl.myDsl.Fonction;
import org.xtext.example.mydsl.myDsl.For;
import org.xtext.example.mydsl.myDsl.ForEach;
import org.xtext.example.mydsl.myDsl.If;
import org.xtext.example.mydsl.myDsl.Input;
import org.xtext.example.mydsl.myDsl.Lexpr;
import org.xtext.example.mydsl.myDsl.Nill;
import org.xtext.example.mydsl.myDsl.Nop;
import org.xtext.example.mydsl.myDsl.OpAccSucc;
import org.xtext.example.mydsl.myDsl.OpConstructeur;
import org.xtext.example.mydsl.myDsl.Output;
import org.xtext.example.mydsl.myDsl.Program;
import org.xtext.example.mydsl.myDsl.Variable;
import org.xtext.example.mydsl.myDsl.While;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class MyDslGenerator extends AbstractGenerator {
  private int nbCmdImbrique = 0;
  
  private int indentALl = 2;
  
  private int indentFOR = 2;
  
  private int indentIF = 2;
  
  private int indentWHILE = 2;
  
  private int indentFOREACH = 2;
  
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    TreeIterator<EObject> _allContents = resource.getAllContents();
    Iterable<EObject> _iterable = IteratorExtensions.<EObject>toIterable(_allContents);
    Iterable<Program> _filter = Iterables.<Program>filter(_iterable, Program.class);
    for (final Program e : _filter) {
      String _className = this.className(resource);
      String _plus = (_className + ".whpp");
      String _compile = this.compile(e);
      fsa.generateFile(_plus, _compile);
    }
  }
  
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context, final int all, final int si, final int pour, final int pourEach, final int tq) {
    this.indentALl = all;
    this.indentFOR = pour;
    this.indentIF = si;
    this.indentWHILE = tq;
    this.indentFOREACH = pourEach;
    TreeIterator<EObject> _allContents = resource.getAllContents();
    Iterable<EObject> _iterable = IteratorExtensions.<EObject>toIterable(_allContents);
    Iterable<Program> _filter = Iterables.<Program>filter(_iterable, Program.class);
    for (final Program e : _filter) {
      String _className = this.className(resource);
      String _plus = (_className + ".whpp");
      String _compile = this.compile(e);
      fsa.generateFile(_plus, _compile);
    }
  }
  
  public String className(final Resource res) {
    URI _uRI = res.getURI();
    String name = _uRI.lastSegment();
    int _indexOf = name.indexOf(".");
    return name.substring(0, _indexOf);
  }
  
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context, final String sortie, final int all, final int si, final int pour, final int pourEach, final int tq) {
    TreeIterator<EObject> _allContents = resource.getAllContents();
    Iterable<EObject> _iterable = IteratorExtensions.<EObject>toIterable(_allContents);
    Iterable<Program> _filter = Iterables.<Program>filter(_iterable, Program.class);
    for (final Program e : _filter) {
      String _compile = this.compile(e);
      fsa.generateFile(sortie, _compile);
    }
  }
  
  public String compile(final Program program) {
    String result = "";
    EList<Fonction> _fonctions = program.getFonctions();
    for (final Fonction f : _fonctions) {
      String _result = result;
      CharSequence _compile = this.compile(f);
      result = (_result + _compile);
    }
    return result;
  }
  
  public CharSequence compile(final Fonction fonction) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("function ");
    String _nom = fonction.getNom();
    _builder.append(_nom, "");
    _builder.append(":");
    _builder.newLineIfNotEmpty();
    _builder.append("read ");
    {
      Input _in = fonction.getIn();
      EList<String> _in_1 = _in.getIn();
      boolean _hasElements = false;
      for(final String param : _in_1) {
        if (!_hasElements) {
          _hasElements = true;
        } else {
          _builder.appendImmediate(", ", "");
        }
        _builder.append(param, "");
      }
    }
    _builder.newLineIfNotEmpty();
    _builder.append("%");
    _builder.newLine();
    Commandes _commandes = fonction.getCommandes();
    String _compile = this.compile(_commandes);
    _builder.append(_compile, "");
    _builder.newLineIfNotEmpty();
    _builder.append("%");
    _builder.newLine();
    _builder.append("write ");
    {
      Output _out = fonction.getOut();
      EList<String> _out_1 = _out.getOut();
      boolean _hasElements_1 = false;
      for(final String result : _out_1) {
        if (!_hasElements_1) {
          _hasElements_1 = true;
        } else {
          _builder.appendImmediate(", ", "");
        }
        _builder.append(result, "");
      }
    }
    _builder.newLineIfNotEmpty();
    return _builder;
  }
  
  public String compile(final Commandes cmds) {
    String affichage = "";
    EList<Commande> _commandes = cmds.getCommandes();
    boolean _isEmpty = _commandes.isEmpty();
    boolean _not = (!_isEmpty);
    if (_not) {
      Commande _commande = cmds.getCommande();
      String _compile = this.compile(_commande);
      String _plus = (_compile + " ;\n");
      affichage = _plus;
      int nbCommandes = 0;
      EList<Commande> _commandes_1 = cmds.getCommandes();
      for (final Commande cmd : _commandes_1) {
        EList<Commande> _commandes_2 = cmds.getCommandes();
        int _size = _commandes_2.size();
        int _minus = (_size - 1);
        boolean _equals = (nbCommandes == _minus);
        if (_equals) {
          String _affichage = affichage;
          String _compile_1 = this.compile(cmd);
          affichage = (_affichage + _compile_1);
        } else {
          String _affichage_1 = affichage;
          String _compile_2 = this.compile(cmd);
          String _plus_1 = (_compile_2 + " ;\n");
          affichage = (_affichage_1 + _plus_1);
          nbCommandes++;
        }
      }
    } else {
      Commande _commande_1 = cmds.getCommande();
      String _compile_3 = this.compile(_commande_1);
      affichage = _compile_3;
    }
    return affichage;
  }
  
  public String compile(final Commande cmd) {
    EObject _commande = cmd.getCommande();
    if ((_commande instanceof Nop)) {
      String _indentation = this.indentation((this.nbCmdImbrique + 1), "all");
      return (_indentation + "nop");
    }
    EObject _commande_1 = cmd.getCommande();
    if ((_commande_1 instanceof Affectation)) {
      String _indentation_1 = this.indentation((this.nbCmdImbrique + 1), "all");
      EObject _commande_2 = cmd.getCommande();
      String _compile = this.compile(((Affectation) _commande_2));
      return (_indentation_1 + _compile);
    }
    EObject _commande_3 = cmd.getCommande();
    if ((_commande_3 instanceof If)) {
      EObject _commande_4 = cmd.getCommande();
      return this.compile(((If) _commande_4));
    }
    EObject _commande_5 = cmd.getCommande();
    if ((_commande_5 instanceof For)) {
      EObject _commande_6 = cmd.getCommande();
      return this.compile(((For) _commande_6));
    }
    EObject _commande_7 = cmd.getCommande();
    if ((_commande_7 instanceof While)) {
      EObject _commande_8 = cmd.getCommande();
      return this.compile(((While) _commande_8));
    }
    EObject _commande_9 = cmd.getCommande();
    if ((_commande_9 instanceof ForEach)) {
      EObject _commande_10 = cmd.getCommande();
      return this.compile(((ForEach) _commande_10));
    }
    return null;
  }
  
  public String compile(final ForEach poureach) {
    this.nbCmdImbrique++;
    String _indentation = this.indentation(this.nbCmdImbrique, "foreach");
    String _plus = (_indentation + "foreach ");
    Expression _elem = poureach.getElem();
    String _compile = this.compile(_elem);
    String _plus_1 = (_plus + _compile);
    String _plus_2 = (_plus_1 + " in ");
    Expression _ensemble = poureach.getEnsemble();
    String _compile_1 = this.compile(_ensemble);
    String _plus_3 = (_plus_2 + _compile_1);
    String _plus_4 = (_plus_3 + " do\n");
    Commandes _cmdsFor = poureach.getCmdsFor();
    Object _compile_2 = this.compile(_cmdsFor);
    String _plus_5 = (_plus_4 + _compile_2);
    String _plus_6 = (_plus_5 + "\n");
    String _indentation_1 = this.indentation(this.nbCmdImbrique, "foreach");
    String _plus_7 = (_plus_6 + _indentation_1);
    String result = (_plus_7 + "od");
    this.nbCmdImbrique--;
    return result;
  }
  
  public String compile(final While tq) {
    this.nbCmdImbrique++;
    String _indentation = this.indentation(this.nbCmdImbrique, "while");
    String _plus = (_indentation + "while ");
    Expression _cond = tq.getCond();
    String _compile = this.compile(_cond);
    String _plus_1 = (_plus + _compile);
    String _plus_2 = (_plus_1 + " do\n");
    Commandes _cmdsWh = tq.getCmdsWh();
    Object _compile_1 = this.compile(_cmdsWh);
    String _plus_3 = (_plus_2 + _compile_1);
    String _plus_4 = (_plus_3 + "\n");
    String _indentation_1 = this.indentation(this.nbCmdImbrique, "while");
    String _plus_5 = (_plus_4 + _indentation_1);
    String result = (_plus_5 + "od");
    this.nbCmdImbrique--;
    return result;
  }
  
  public String compile(final For pour) {
    this.nbCmdImbrique++;
    String _indentation = this.indentation(this.nbCmdImbrique, "for");
    String _plus = (_indentation + "for ");
    Expression _cond = pour.getCond();
    String _compile = this.compile(_cond);
    String _plus_1 = (_plus + _compile);
    String _plus_2 = (_plus_1 + " do\n");
    Commandes _cmdsFor = pour.getCmdsFor();
    Object _compile_1 = this.compile(_cmdsFor);
    String _plus_3 = (_plus_2 + _compile_1);
    String _plus_4 = (_plus_3 + "\n");
    String _indentation_1 = this.indentation(this.nbCmdImbrique, "for");
    String _plus_5 = (_plus_4 + _indentation_1);
    String result = (_plus_5 + "od");
    this.nbCmdImbrique--;
    return result;
  }
  
  public String compile(final If si) {
    this.nbCmdImbrique++;
    String _indentation = this.indentation(this.nbCmdImbrique, "if");
    String _plus = (_indentation + "if ");
    Expression _cond = si.getCond();
    String _compile = this.compile(_cond);
    String _plus_1 = (_plus + _compile);
    String _plus_2 = (_plus_1 + " then\n");
    Commandes _cmdsIf = si.getCmdsIf();
    Object _compile_1 = this.compile(_cmdsIf);
    String result = (_plus_2 + _compile_1);
    Commandes _cmdsElse = si.getCmdsElse();
    boolean _notEquals = (!Objects.equal(_cmdsElse, null));
    if (_notEquals) {
      String _result = result;
      String _indentation_1 = this.indentation(this.nbCmdImbrique, "if");
      String _plus_3 = ("\n" + _indentation_1);
      String _plus_4 = (_plus_3 + "else\n");
      Commandes _cmdsElse_1 = si.getCmdsElse();
      Object _compile_2 = this.compile(_cmdsElse_1);
      String _plus_5 = (_plus_4 + _compile_2);
      result = (_result + _plus_5);
    }
    String _result_1 = result;
    String _indentation_2 = this.indentation(this.nbCmdImbrique, "if");
    String _plus_6 = ("\n" + _indentation_2);
    String _plus_7 = (_plus_6 + "fi");
    result = (_result_1 + _plus_7);
    this.nbCmdImbrique--;
    return result;
  }
  
  public String compile(final Affectation affect) {
    String result = "";
    EList<Variable> _variable = affect.getVariable();
    boolean _equals = Objects.equal(_variable, Integer.valueOf(1));
    if (_equals) {
      EList<Variable> _variable_1 = affect.getVariable();
      Variable _get = _variable_1.get(0);
      String _variable_2 = _get.getVariable();
      String _plus = (_variable_2 + " := ");
      EList<Expression> _elm = affect.getElm();
      Expression _get_1 = _elm.get(0);
      String _compile = this.compile(_get_1);
      return (_plus + _compile);
    } else {
      EList<Variable> _variable_3 = affect.getVariable();
      int _size = _variable_3.size();
      ExclusiveRange _doubleDotLessThan = new ExclusiveRange(0, _size, true);
      for (final Integer i : _doubleDotLessThan) {
        EList<Variable> _variable_4 = affect.getVariable();
        int _size_1 = _variable_4.size();
        int _minus = (_size_1 - 1);
        boolean _lessThan = ((i).intValue() < _minus);
        if (_lessThan) {
          String _result = result;
          EList<Variable> _variable_5 = affect.getVariable();
          Variable _get_2 = _variable_5.get((i).intValue());
          String _variable_6 = _get_2.getVariable();
          String _plus_1 = (_variable_6 + ", ");
          result = (_result + _plus_1);
        } else {
          String _result_1 = result;
          EList<Variable> _variable_7 = affect.getVariable();
          Variable _get_3 = _variable_7.get((i).intValue());
          String _variable_8 = _get_3.getVariable();
          String _plus_2 = (_variable_8 + " := ");
          result = (_result_1 + _plus_2);
        }
      }
      EList<Expression> _elm_1 = affect.getElm();
      int _size_2 = _elm_1.size();
      ExclusiveRange _doubleDotLessThan_1 = new ExclusiveRange(0, _size_2, true);
      for (final Integer i_1 : _doubleDotLessThan_1) {
        EList<Expression> _elm_2 = affect.getElm();
        int _size_3 = _elm_2.size();
        int _minus_1 = (_size_3 - 1);
        boolean _lessThan_1 = ((i_1).intValue() < _minus_1);
        if (_lessThan_1) {
          String _result_2 = result;
          EList<Expression> _elm_3 = affect.getElm();
          Expression _get_4 = _elm_3.get((i_1).intValue());
          String _compile_1 = this.compile(_get_4);
          String _plus_3 = (_compile_1 + ", ");
          result = (_result_2 + _plus_3);
        } else {
          String _result_3 = result;
          EList<Expression> _elm_4 = affect.getElm();
          Expression _get_5 = _elm_4.get((i_1).intValue());
          String _compile_2 = this.compile(_get_5);
          result = (_result_3 + _compile_2);
        }
      }
    }
    return result;
  }
  
  public String compile(final Expression expression) {
    ExprSimple _exprs = expression.getExprs();
    boolean _notEquals = (!Objects.equal(_exprs, null));
    if (_notEquals) {
      ExprSimple _exprs_1 = expression.getExprs();
      return this.compile(_exprs_1);
    } else {
      Condition _cond = expression.getCond();
      boolean _notEquals_1 = (!Objects.equal(_cond, null));
      if (_notEquals_1) {
        Condition _cond_1 = expression.getCond();
        return this.compile(_cond_1);
      }
    }
    return null;
  }
  
  public String compile(final Condition cond) {
    ExprSimple _e1 = cond.getE1();
    boolean _notEquals = (!Objects.equal(_e1, null));
    if (_notEquals) {
      ExprSimple _e1_1 = cond.getE1();
      String _compile = this.compile(_e1_1);
      String _plus = (_compile + " ");
      COMPARATEUR _comp = cond.getComp();
      String _comparateur = _comp.getComparateur();
      String _plus_1 = (_plus + _comparateur);
      String _plus_2 = (_plus_1 + " ");
      Expression _e2 = cond.getE2();
      Object _compile_1 = this.compile(_e2);
      return (_plus_2 + _compile_1);
    } else {
      return " pas encore fait ça bug ";
    }
  }
  
  public String compile(final ExprSimple expr) {
    ABin _abin = expr.getAbin();
    boolean _notEquals = (!Objects.equal(_abin, null));
    if (_notEquals) {
      ABin _abin_1 = expr.getAbin();
      OpConstructeur _op = _abin_1.getOp();
      String _op_1 = _op.getOp();
      String _plus = ("(" + _op_1);
      String _plus_1 = (_plus + " ");
      ABin _abin_2 = expr.getAbin();
      Expression _e1 = _abin_2.getE1();
      Object _compile = this.compile(_e1);
      String _plus_2 = (_plus_1 + _compile);
      String _plus_3 = (_plus_2 + " ");
      ABin _abin_3 = expr.getAbin();
      Expression _e2 = _abin_3.getE2();
      Object _compile_1 = this.compile(_e2);
      String _plus_4 = (_plus_3 + _compile_1);
      return (_plus_4 + ")");
    }
    Nill _nil = expr.getNil();
    boolean _notEquals_1 = (!Objects.equal(_nil, null));
    if (_notEquals_1) {
      return "nil";
    }
    Variable _variable = expr.getVariable();
    boolean _notEquals_2 = (!Objects.equal(_variable, null));
    if (_notEquals_2) {
      Variable _variable_1 = expr.getVariable();
      return _variable_1.getVariable();
    }
    String _symb = expr.getSymb();
    boolean _notEquals_3 = (!Objects.equal(_symb, null));
    if (_notEquals_3) {
      return expr.getSymb();
    }
    AccSucc _accsucc = expr.getAccsucc();
    boolean _notEquals_4 = (!Objects.equal(_accsucc, null));
    if (_notEquals_4) {
      AccSucc _accsucc_1 = expr.getAccsucc();
      OpAccSucc _op_2 = _accsucc_1.getOp();
      String _op_3 = _op_2.getOp();
      String _plus_5 = ("(" + _op_3);
      String _plus_6 = (_plus_5 + " ");
      AccSucc _accsucc_2 = expr.getAccsucc();
      ExprSimple _expr = _accsucc_2.getExpr();
      Object _compile_2 = this.compile(_expr);
      String _plus_7 = (_plus_6 + _compile_2);
      return (_plus_7 + ")");
    }
    ElemSimple _elemSimple = expr.getElemSimple();
    boolean _notEquals_5 = (!Objects.equal(_elemSimple, null));
    if (_notEquals_5) {
      ElemSimple _elemSimple_1 = expr.getElemSimple();
      String _symb_1 = _elemSimple_1.getSymb();
      String _plus_8 = ("(" + _symb_1);
      String _plus_9 = (_plus_8 + " ");
      ElemSimple _elemSimple_2 = expr.getElemSimple();
      Lexpr _lexpr = _elemSimple_2.getLexpr();
      String _plus_10 = (_plus_9 + _lexpr);
      String _plus_11 = (_plus_10 + " ");
      ElemSimple _elemSimple_3 = expr.getElemSimple();
      String _plus_12 = (_plus_11 + _elemSimple_3);
      return (_plus_12 + ")");
    }
    return null;
  }
  
  public String indentation(final int nb, final String type) {
    int i = 1;
    String result = "";
    boolean _equals = type.equals("all");
    if (_equals) {
      while ((i < (nb * this.indentALl))) {
        {
          String _result = result;
          result = (_result + " ");
          i++;
        }
      }
    }
    boolean _equals_1 = type.equals("while");
    if (_equals_1) {
      while ((i < (nb * this.indentWHILE))) {
        {
          String _result = result;
          result = (_result + " ");
          i++;
        }
      }
    }
    boolean _equals_2 = type.equals("for");
    if (_equals_2) {
      while ((i < (nb * this.indentFOR))) {
        {
          String _result = result;
          result = (_result + " ");
          i++;
        }
      }
    }
    boolean _equals_3 = type.equals("if");
    if (_equals_3) {
      while ((i < (nb * this.indentIF))) {
        {
          String _result = result;
          result = (_result + " ");
          i++;
        }
      }
    }
    boolean _equals_4 = type.equals("foreach");
    if (_equals_4) {
      while ((i < (nb * this.indentFOREACH))) {
        {
          String _result = result;
          result = (_result + " ");
          i++;
        }
      }
    }
    return result;
  }
}
