/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>COMPARATEUR</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.COMPARATEUR#getComparateur <em>Comparateur</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getCOMPARATEUR()
 * @model
 * @generated
 */
public interface COMPARATEUR extends EObject
{
  /**
   * Returns the value of the '<em><b>Comparateur</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Comparateur</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Comparateur</em>' attribute.
   * @see #setComparateur(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getCOMPARATEUR_Comparateur()
   * @model
   * @generated
   */
  String getComparateur();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.COMPARATEUR#getComparateur <em>Comparateur</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Comparateur</em>' attribute.
   * @see #getComparateur()
   * @generated
   */
  void setComparateur(String value);

} // COMPARATEUR
