/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Condition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Condition#getE1 <em>E1</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Condition#getComp <em>Comp</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Condition#getE2 <em>E2</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getCondition()
 * @model
 * @generated
 */
public interface Condition extends EObject
{
  /**
   * Returns the value of the '<em><b>E1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>E1</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>E1</em>' containment reference.
   * @see #setE1(ExprSimple)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getCondition_E1()
   * @model containment="true"
   * @generated
   */
  ExprSimple getE1();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Condition#getE1 <em>E1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>E1</em>' containment reference.
   * @see #getE1()
   * @generated
   */
  void setE1(ExprSimple value);

  /**
   * Returns the value of the '<em><b>Comp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Comp</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Comp</em>' containment reference.
   * @see #setComp(COMPARATEUR)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getCondition_Comp()
   * @model containment="true"
   * @generated
   */
  COMPARATEUR getComp();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Condition#getComp <em>Comp</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Comp</em>' containment reference.
   * @see #getComp()
   * @generated
   */
  void setComp(COMPARATEUR value);

  /**
   * Returns the value of the '<em><b>E2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>E2</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>E2</em>' containment reference.
   * @see #setE2(Expression)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getCondition_E2()
   * @model containment="true"
   * @generated
   */
  Expression getE2();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Condition#getE2 <em>E2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>E2</em>' containment reference.
   * @see #getE2()
   * @generated
   */
  void setE2(Expression value);

} // Condition
