/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Elem Simple</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.ElemSimple#getSymb <em>Symb</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.ElemSimple#getLexpr <em>Lexpr</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getElemSimple()
 * @model
 * @generated
 */
public interface ElemSimple extends EObject
{
  /**
   * Returns the value of the '<em><b>Symb</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Symb</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Symb</em>' attribute.
   * @see #setSymb(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getElemSimple_Symb()
   * @model
   * @generated
   */
  String getSymb();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.ElemSimple#getSymb <em>Symb</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Symb</em>' attribute.
   * @see #getSymb()
   * @generated
   */
  void setSymb(String value);

  /**
   * Returns the value of the '<em><b>Lexpr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Lexpr</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lexpr</em>' containment reference.
   * @see #setLexpr(Lexpr)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getElemSimple_Lexpr()
   * @model containment="true"
   * @generated
   */
  Lexpr getLexpr();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.ElemSimple#getLexpr <em>Lexpr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lexpr</em>' containment reference.
   * @see #getLexpr()
   * @generated
   */
  void setLexpr(Lexpr value);

} // ElemSimple
