/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>If</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.If#getCond <em>Cond</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.If#getCmdsIf <em>Cmds If</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.If#getCmdsElse <em>Cmds Else</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getIf()
 * @model
 * @generated
 */
public interface If extends EObject
{
  /**
   * Returns the value of the '<em><b>Cond</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Cond</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cond</em>' containment reference.
   * @see #setCond(Expression)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getIf_Cond()
   * @model containment="true"
   * @generated
   */
  Expression getCond();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.If#getCond <em>Cond</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cond</em>' containment reference.
   * @see #getCond()
   * @generated
   */
  void setCond(Expression value);

  /**
   * Returns the value of the '<em><b>Cmds If</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Cmds If</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cmds If</em>' containment reference.
   * @see #setCmdsIf(Commandes)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getIf_CmdsIf()
   * @model containment="true"
   * @generated
   */
  Commandes getCmdsIf();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.If#getCmdsIf <em>Cmds If</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cmds If</em>' containment reference.
   * @see #getCmdsIf()
   * @generated
   */
  void setCmdsIf(Commandes value);

  /**
   * Returns the value of the '<em><b>Cmds Else</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Cmds Else</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cmds Else</em>' containment reference.
   * @see #setCmdsElse(Commandes)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getIf_CmdsElse()
   * @model containment="true"
   * @generated
   */
  Commandes getCmdsElse();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.If#getCmdsElse <em>Cmds Else</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cmds Else</em>' containment reference.
   * @see #getCmdsElse()
   * @generated
   */
  void setCmdsElse(Commandes value);

} // If
