/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.myDsl.MyDslFactory
 * @model kind="package"
 * @generated
 */
public interface MyDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/MyDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslPackage eINSTANCE = org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ProgramImpl <em>Program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ProgramImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getProgram()
   * @generated
   */
  int PROGRAM = 0;

  /**
   * The feature id for the '<em><b>Fonctions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__FONCTIONS = 0;

  /**
   * The number of structural features of the '<em>Program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.FonctionImpl <em>Fonction</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.FonctionImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getFonction()
   * @generated
   */
  int FONCTION = 1;

  /**
   * The feature id for the '<em><b>Nom</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FONCTION__NOM = 0;

  /**
   * The feature id for the '<em><b>In</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FONCTION__IN = 1;

  /**
   * The feature id for the '<em><b>Commandes</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FONCTION__COMMANDES = 2;

  /**
   * The feature id for the '<em><b>Out</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FONCTION__OUT = 3;

  /**
   * The number of structural features of the '<em>Fonction</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FONCTION_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.CommandesImpl <em>Commandes</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.CommandesImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getCommandes()
   * @generated
   */
  int COMMANDES = 2;

  /**
   * The feature id for the '<em><b>Commande</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMANDES__COMMANDE = 0;

  /**
   * The feature id for the '<em><b>Commandes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMANDES__COMMANDES = 1;

  /**
   * The number of structural features of the '<em>Commandes</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMANDES_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.CommandeImpl <em>Commande</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.CommandeImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getCommande()
   * @generated
   */
  int COMMANDE = 3;

  /**
   * The feature id for the '<em><b>Commande</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMANDE__COMMANDE = 0;

  /**
   * The number of structural features of the '<em>Commande</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMANDE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.AffectationImpl <em>Affectation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.AffectationImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getAffectation()
   * @generated
   */
  int AFFECTATION = 4;

  /**
   * The feature id for the '<em><b>Variable</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AFFECTATION__VARIABLE = 0;

  /**
   * The feature id for the '<em><b>Elm</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AFFECTATION__ELM = 1;

  /**
   * The number of structural features of the '<em>Affectation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AFFECTATION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.IfImpl <em>If</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.IfImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getIf()
   * @generated
   */
  int IF = 5;

  /**
   * The feature id for the '<em><b>Cond</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF__COND = 0;

  /**
   * The feature id for the '<em><b>Cmds If</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF__CMDS_IF = 1;

  /**
   * The feature id for the '<em><b>Cmds Else</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF__CMDS_ELSE = 2;

  /**
   * The number of structural features of the '<em>If</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.WhileImpl <em>While</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.WhileImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getWhile()
   * @generated
   */
  int WHILE = 6;

  /**
   * The feature id for the '<em><b>Cond</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHILE__COND = 0;

  /**
   * The feature id for the '<em><b>Cmds Wh</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHILE__CMDS_WH = 1;

  /**
   * The number of structural features of the '<em>While</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHILE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ForImpl <em>For</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ForImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getFor()
   * @generated
   */
  int FOR = 7;

  /**
   * The feature id for the '<em><b>Cond</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR__COND = 0;

  /**
   * The feature id for the '<em><b>Cmds For</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR__CMDS_FOR = 1;

  /**
   * The number of structural features of the '<em>For</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ForEachImpl <em>For Each</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ForEachImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getForEach()
   * @generated
   */
  int FOR_EACH = 8;

  /**
   * The feature id for the '<em><b>Elem</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR_EACH__ELEM = 0;

  /**
   * The feature id for the '<em><b>Ensemble</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR_EACH__ENSEMBLE = 1;

  /**
   * The feature id for the '<em><b>Cmds For</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR_EACH__CMDS_FOR = 2;

  /**
   * The number of structural features of the '<em>For Each</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR_EACH_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.NopImpl <em>Nop</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.NopImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getNop()
   * @generated
   */
  int NOP = 9;

  /**
   * The feature id for the '<em><b>Nop</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOP__NOP = 0;

  /**
   * The number of structural features of the '<em>Nop</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOP_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ExpressionImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 10;

  /**
   * The feature id for the '<em><b>Cond</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__COND = 0;

  /**
   * The feature id for the '<em><b>Exprs</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__EXPRS = 1;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ExprSimpleImpl <em>Expr Simple</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ExprSimpleImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getExprSimple()
   * @generated
   */
  int EXPR_SIMPLE = 11;

  /**
   * The feature id for the '<em><b>Nil</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_SIMPLE__NIL = 0;

  /**
   * The feature id for the '<em><b>Variable</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_SIMPLE__VARIABLE = 1;

  /**
   * The feature id for the '<em><b>Abin</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_SIMPLE__ABIN = 2;

  /**
   * The feature id for the '<em><b>Symb</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_SIMPLE__SYMB = 3;

  /**
   * The feature id for the '<em><b>Accsucc</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_SIMPLE__ACCSUCC = 4;

  /**
   * The feature id for the '<em><b>Elem Simple</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_SIMPLE__ELEM_SIMPLE = 5;

  /**
   * The number of structural features of the '<em>Expr Simple</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_SIMPLE_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.VariableImpl <em>Variable</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.VariableImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getVariable()
   * @generated
   */
  int VARIABLE = 12;

  /**
   * The feature id for the '<em><b>Variable</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE__VARIABLE = 0;

  /**
   * The number of structural features of the '<em>Variable</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.LexprImpl <em>Lexpr</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.LexprImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getLexpr()
   * @generated
   */
  int LEXPR = 13;

  /**
   * The feature id for the '<em><b>E1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEXPR__E1 = 0;

  /**
   * The feature id for the '<em><b>Lexpr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEXPR__LEXPR = 1;

  /**
   * The number of structural features of the '<em>Lexpr</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEXPR_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ElemSimpleImpl <em>Elem Simple</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ElemSimpleImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getElemSimple()
   * @generated
   */
  int ELEM_SIMPLE = 14;

  /**
   * The feature id for the '<em><b>Symb</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEM_SIMPLE__SYMB = 0;

  /**
   * The feature id for the '<em><b>Lexpr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEM_SIMPLE__LEXPR = 1;

  /**
   * The number of structural features of the '<em>Elem Simple</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEM_SIMPLE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ConditionImpl <em>Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ConditionImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getCondition()
   * @generated
   */
  int CONDITION = 15;

  /**
   * The feature id for the '<em><b>E1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION__E1 = 0;

  /**
   * The feature id for the '<em><b>Comp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION__COMP = 1;

  /**
   * The feature id for the '<em><b>E2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION__E2 = 2;

  /**
   * The number of structural features of the '<em>Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.ABinImpl <em>ABin</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.ABinImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getABin()
   * @generated
   */
  int ABIN = 16;

  /**
   * The feature id for the '<em><b>Op</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABIN__OP = 0;

  /**
   * The feature id for the '<em><b>E1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABIN__E1 = 1;

  /**
   * The feature id for the '<em><b>E2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABIN__E2 = 2;

  /**
   * The number of structural features of the '<em>ABin</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABIN_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.AccSuccImpl <em>Acc Succ</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.AccSuccImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getAccSucc()
   * @generated
   */
  int ACC_SUCC = 17;

  /**
   * The feature id for the '<em><b>Op</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACC_SUCC__OP = 0;

  /**
   * The feature id for the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACC_SUCC__EXPR = 1;

  /**
   * The number of structural features of the '<em>Acc Succ</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACC_SUCC_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.OutputImpl <em>Output</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.OutputImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getOutput()
   * @generated
   */
  int OUTPUT = 18;

  /**
   * The feature id for the '<em><b>Out</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUTPUT__OUT = 0;

  /**
   * The number of structural features of the '<em>Output</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUTPUT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.InputImpl <em>Input</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.InputImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getInput()
   * @generated
   */
  int INPUT = 19;

  /**
   * The feature id for the '<em><b>In</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INPUT__IN = 0;

  /**
   * The number of structural features of the '<em>Input</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INPUT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.NillImpl <em>Nill</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.NillImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getNill()
   * @generated
   */
  int NILL = 20;

  /**
   * The feature id for the '<em><b>Nil</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NILL__NIL = 0;

  /**
   * The number of structural features of the '<em>Nill</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NILL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.OpAccSuccImpl <em>Op Acc Succ</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.OpAccSuccImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getOpAccSucc()
   * @generated
   */
  int OP_ACC_SUCC = 21;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OP_ACC_SUCC__OP = 0;

  /**
   * The number of structural features of the '<em>Op Acc Succ</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OP_ACC_SUCC_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.NotImpl <em>Not</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.NotImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getNot()
   * @generated
   */
  int NOT = 22;

  /**
   * The feature id for the '<em><b>E1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOT__E1 = CONDITION__E1;

  /**
   * The feature id for the '<em><b>Comp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOT__COMP = CONDITION__COMP;

  /**
   * The feature id for the '<em><b>E2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOT__E2 = CONDITION__E2;

  /**
   * The feature id for the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOT__EXPR = CONDITION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Not</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOT__NOT = CONDITION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Not</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOT_FEATURE_COUNT = CONDITION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.OpConstructeurImpl <em>Op Constructeur</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.OpConstructeurImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getOpConstructeur()
   * @generated
   */
  int OP_CONSTRUCTEUR = 23;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OP_CONSTRUCTEUR__OP = 0;

  /**
   * The number of structural features of the '<em>Op Constructeur</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OP_CONSTRUCTEUR_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.COMPARATEURImpl <em>COMPARATEUR</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.COMPARATEURImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getCOMPARATEUR()
   * @generated
   */
  int COMPARATEUR = 24;

  /**
   * The feature id for the '<em><b>Comparateur</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARATEUR__COMPARATEUR = 0;

  /**
   * The number of structural features of the '<em>COMPARATEUR</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARATEUR_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Program <em>Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Program</em>'.
   * @see org.xtext.example.mydsl.myDsl.Program
   * @generated
   */
  EClass getProgram();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Program#getFonctions <em>Fonctions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Fonctions</em>'.
   * @see org.xtext.example.mydsl.myDsl.Program#getFonctions()
   * @see #getProgram()
   * @generated
   */
  EReference getProgram_Fonctions();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Fonction <em>Fonction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Fonction</em>'.
   * @see org.xtext.example.mydsl.myDsl.Fonction
   * @generated
   */
  EClass getFonction();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Fonction#getNom <em>Nom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nom</em>'.
   * @see org.xtext.example.mydsl.myDsl.Fonction#getNom()
   * @see #getFonction()
   * @generated
   */
  EAttribute getFonction_Nom();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Fonction#getIn <em>In</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>In</em>'.
   * @see org.xtext.example.mydsl.myDsl.Fonction#getIn()
   * @see #getFonction()
   * @generated
   */
  EReference getFonction_In();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Fonction#getCommandes <em>Commandes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Commandes</em>'.
   * @see org.xtext.example.mydsl.myDsl.Fonction#getCommandes()
   * @see #getFonction()
   * @generated
   */
  EReference getFonction_Commandes();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Fonction#getOut <em>Out</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Out</em>'.
   * @see org.xtext.example.mydsl.myDsl.Fonction#getOut()
   * @see #getFonction()
   * @generated
   */
  EReference getFonction_Out();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Commandes <em>Commandes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Commandes</em>'.
   * @see org.xtext.example.mydsl.myDsl.Commandes
   * @generated
   */
  EClass getCommandes();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Commandes#getCommande <em>Commande</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Commande</em>'.
   * @see org.xtext.example.mydsl.myDsl.Commandes#getCommande()
   * @see #getCommandes()
   * @generated
   */
  EReference getCommandes_Commande();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Commandes#getCommandes <em>Commandes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Commandes</em>'.
   * @see org.xtext.example.mydsl.myDsl.Commandes#getCommandes()
   * @see #getCommandes()
   * @generated
   */
  EReference getCommandes_Commandes();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Commande <em>Commande</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Commande</em>'.
   * @see org.xtext.example.mydsl.myDsl.Commande
   * @generated
   */
  EClass getCommande();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Commande#getCommande <em>Commande</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Commande</em>'.
   * @see org.xtext.example.mydsl.myDsl.Commande#getCommande()
   * @see #getCommande()
   * @generated
   */
  EReference getCommande_Commande();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Affectation <em>Affectation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Affectation</em>'.
   * @see org.xtext.example.mydsl.myDsl.Affectation
   * @generated
   */
  EClass getAffectation();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Affectation#getVariable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Variable</em>'.
   * @see org.xtext.example.mydsl.myDsl.Affectation#getVariable()
   * @see #getAffectation()
   * @generated
   */
  EReference getAffectation_Variable();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Affectation#getElm <em>Elm</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elm</em>'.
   * @see org.xtext.example.mydsl.myDsl.Affectation#getElm()
   * @see #getAffectation()
   * @generated
   */
  EReference getAffectation_Elm();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.If <em>If</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>If</em>'.
   * @see org.xtext.example.mydsl.myDsl.If
   * @generated
   */
  EClass getIf();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.If#getCond <em>Cond</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Cond</em>'.
   * @see org.xtext.example.mydsl.myDsl.If#getCond()
   * @see #getIf()
   * @generated
   */
  EReference getIf_Cond();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.If#getCmdsIf <em>Cmds If</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Cmds If</em>'.
   * @see org.xtext.example.mydsl.myDsl.If#getCmdsIf()
   * @see #getIf()
   * @generated
   */
  EReference getIf_CmdsIf();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.If#getCmdsElse <em>Cmds Else</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Cmds Else</em>'.
   * @see org.xtext.example.mydsl.myDsl.If#getCmdsElse()
   * @see #getIf()
   * @generated
   */
  EReference getIf_CmdsElse();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.While <em>While</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>While</em>'.
   * @see org.xtext.example.mydsl.myDsl.While
   * @generated
   */
  EClass getWhile();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.While#getCond <em>Cond</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Cond</em>'.
   * @see org.xtext.example.mydsl.myDsl.While#getCond()
   * @see #getWhile()
   * @generated
   */
  EReference getWhile_Cond();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.While#getCmdsWh <em>Cmds Wh</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Cmds Wh</em>'.
   * @see org.xtext.example.mydsl.myDsl.While#getCmdsWh()
   * @see #getWhile()
   * @generated
   */
  EReference getWhile_CmdsWh();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.For <em>For</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>For</em>'.
   * @see org.xtext.example.mydsl.myDsl.For
   * @generated
   */
  EClass getFor();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.For#getCond <em>Cond</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Cond</em>'.
   * @see org.xtext.example.mydsl.myDsl.For#getCond()
   * @see #getFor()
   * @generated
   */
  EReference getFor_Cond();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.For#getCmdsFor <em>Cmds For</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Cmds For</em>'.
   * @see org.xtext.example.mydsl.myDsl.For#getCmdsFor()
   * @see #getFor()
   * @generated
   */
  EReference getFor_CmdsFor();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.ForEach <em>For Each</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>For Each</em>'.
   * @see org.xtext.example.mydsl.myDsl.ForEach
   * @generated
   */
  EClass getForEach();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.ForEach#getElem <em>Elem</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Elem</em>'.
   * @see org.xtext.example.mydsl.myDsl.ForEach#getElem()
   * @see #getForEach()
   * @generated
   */
  EReference getForEach_Elem();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.ForEach#getEnsemble <em>Ensemble</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Ensemble</em>'.
   * @see org.xtext.example.mydsl.myDsl.ForEach#getEnsemble()
   * @see #getForEach()
   * @generated
   */
  EReference getForEach_Ensemble();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.ForEach#getCmdsFor <em>Cmds For</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Cmds For</em>'.
   * @see org.xtext.example.mydsl.myDsl.ForEach#getCmdsFor()
   * @see #getForEach()
   * @generated
   */
  EReference getForEach_CmdsFor();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Nop <em>Nop</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Nop</em>'.
   * @see org.xtext.example.mydsl.myDsl.Nop
   * @generated
   */
  EClass getNop();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Nop#getNop <em>Nop</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nop</em>'.
   * @see org.xtext.example.mydsl.myDsl.Nop#getNop()
   * @see #getNop()
   * @generated
   */
  EAttribute getNop_Nop();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see org.xtext.example.mydsl.myDsl.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Expression#getCond <em>Cond</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Cond</em>'.
   * @see org.xtext.example.mydsl.myDsl.Expression#getCond()
   * @see #getExpression()
   * @generated
   */
  EReference getExpression_Cond();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Expression#getExprs <em>Exprs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exprs</em>'.
   * @see org.xtext.example.mydsl.myDsl.Expression#getExprs()
   * @see #getExpression()
   * @generated
   */
  EReference getExpression_Exprs();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.ExprSimple <em>Expr Simple</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expr Simple</em>'.
   * @see org.xtext.example.mydsl.myDsl.ExprSimple
   * @generated
   */
  EClass getExprSimple();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.ExprSimple#getNil <em>Nil</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Nil</em>'.
   * @see org.xtext.example.mydsl.myDsl.ExprSimple#getNil()
   * @see #getExprSimple()
   * @generated
   */
  EReference getExprSimple_Nil();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.ExprSimple#getVariable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Variable</em>'.
   * @see org.xtext.example.mydsl.myDsl.ExprSimple#getVariable()
   * @see #getExprSimple()
   * @generated
   */
  EReference getExprSimple_Variable();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.ExprSimple#getAbin <em>Abin</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Abin</em>'.
   * @see org.xtext.example.mydsl.myDsl.ExprSimple#getAbin()
   * @see #getExprSimple()
   * @generated
   */
  EReference getExprSimple_Abin();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.ExprSimple#getSymb <em>Symb</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Symb</em>'.
   * @see org.xtext.example.mydsl.myDsl.ExprSimple#getSymb()
   * @see #getExprSimple()
   * @generated
   */
  EAttribute getExprSimple_Symb();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.ExprSimple#getAccsucc <em>Accsucc</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Accsucc</em>'.
   * @see org.xtext.example.mydsl.myDsl.ExprSimple#getAccsucc()
   * @see #getExprSimple()
   * @generated
   */
  EReference getExprSimple_Accsucc();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.ExprSimple#getElemSimple <em>Elem Simple</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Elem Simple</em>'.
   * @see org.xtext.example.mydsl.myDsl.ExprSimple#getElemSimple()
   * @see #getExprSimple()
   * @generated
   */
  EReference getExprSimple_ElemSimple();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Variable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable</em>'.
   * @see org.xtext.example.mydsl.myDsl.Variable
   * @generated
   */
  EClass getVariable();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Variable#getVariable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Variable</em>'.
   * @see org.xtext.example.mydsl.myDsl.Variable#getVariable()
   * @see #getVariable()
   * @generated
   */
  EAttribute getVariable_Variable();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Lexpr <em>Lexpr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Lexpr</em>'.
   * @see org.xtext.example.mydsl.myDsl.Lexpr
   * @generated
   */
  EClass getLexpr();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Lexpr#getE1 <em>E1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>E1</em>'.
   * @see org.xtext.example.mydsl.myDsl.Lexpr#getE1()
   * @see #getLexpr()
   * @generated
   */
  EReference getLexpr_E1();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Lexpr#getLexpr <em>Lexpr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Lexpr</em>'.
   * @see org.xtext.example.mydsl.myDsl.Lexpr#getLexpr()
   * @see #getLexpr()
   * @generated
   */
  EReference getLexpr_Lexpr();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.ElemSimple <em>Elem Simple</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Elem Simple</em>'.
   * @see org.xtext.example.mydsl.myDsl.ElemSimple
   * @generated
   */
  EClass getElemSimple();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.ElemSimple#getSymb <em>Symb</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Symb</em>'.
   * @see org.xtext.example.mydsl.myDsl.ElemSimple#getSymb()
   * @see #getElemSimple()
   * @generated
   */
  EAttribute getElemSimple_Symb();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.ElemSimple#getLexpr <em>Lexpr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Lexpr</em>'.
   * @see org.xtext.example.mydsl.myDsl.ElemSimple#getLexpr()
   * @see #getElemSimple()
   * @generated
   */
  EReference getElemSimple_Lexpr();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Condition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Condition</em>'.
   * @see org.xtext.example.mydsl.myDsl.Condition
   * @generated
   */
  EClass getCondition();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Condition#getE1 <em>E1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>E1</em>'.
   * @see org.xtext.example.mydsl.myDsl.Condition#getE1()
   * @see #getCondition()
   * @generated
   */
  EReference getCondition_E1();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Condition#getComp <em>Comp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Comp</em>'.
   * @see org.xtext.example.mydsl.myDsl.Condition#getComp()
   * @see #getCondition()
   * @generated
   */
  EReference getCondition_Comp();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Condition#getE2 <em>E2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>E2</em>'.
   * @see org.xtext.example.mydsl.myDsl.Condition#getE2()
   * @see #getCondition()
   * @generated
   */
  EReference getCondition_E2();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.ABin <em>ABin</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>ABin</em>'.
   * @see org.xtext.example.mydsl.myDsl.ABin
   * @generated
   */
  EClass getABin();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.ABin#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Op</em>'.
   * @see org.xtext.example.mydsl.myDsl.ABin#getOp()
   * @see #getABin()
   * @generated
   */
  EReference getABin_Op();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.ABin#getE1 <em>E1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>E1</em>'.
   * @see org.xtext.example.mydsl.myDsl.ABin#getE1()
   * @see #getABin()
   * @generated
   */
  EReference getABin_E1();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.ABin#getE2 <em>E2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>E2</em>'.
   * @see org.xtext.example.mydsl.myDsl.ABin#getE2()
   * @see #getABin()
   * @generated
   */
  EReference getABin_E2();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.AccSucc <em>Acc Succ</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Acc Succ</em>'.
   * @see org.xtext.example.mydsl.myDsl.AccSucc
   * @generated
   */
  EClass getAccSucc();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.AccSucc#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Op</em>'.
   * @see org.xtext.example.mydsl.myDsl.AccSucc#getOp()
   * @see #getAccSucc()
   * @generated
   */
  EReference getAccSucc_Op();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.AccSucc#getExpr <em>Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expr</em>'.
   * @see org.xtext.example.mydsl.myDsl.AccSucc#getExpr()
   * @see #getAccSucc()
   * @generated
   */
  EReference getAccSucc_Expr();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Output <em>Output</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Output</em>'.
   * @see org.xtext.example.mydsl.myDsl.Output
   * @generated
   */
  EClass getOutput();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.example.mydsl.myDsl.Output#getOut <em>Out</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Out</em>'.
   * @see org.xtext.example.mydsl.myDsl.Output#getOut()
   * @see #getOutput()
   * @generated
   */
  EAttribute getOutput_Out();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Input <em>Input</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Input</em>'.
   * @see org.xtext.example.mydsl.myDsl.Input
   * @generated
   */
  EClass getInput();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.example.mydsl.myDsl.Input#getIn <em>In</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>In</em>'.
   * @see org.xtext.example.mydsl.myDsl.Input#getIn()
   * @see #getInput()
   * @generated
   */
  EAttribute getInput_In();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Nill <em>Nill</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Nill</em>'.
   * @see org.xtext.example.mydsl.myDsl.Nill
   * @generated
   */
  EClass getNill();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Nill#getNil <em>Nil</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nil</em>'.
   * @see org.xtext.example.mydsl.myDsl.Nill#getNil()
   * @see #getNill()
   * @generated
   */
  EAttribute getNill_Nil();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.OpAccSucc <em>Op Acc Succ</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Op Acc Succ</em>'.
   * @see org.xtext.example.mydsl.myDsl.OpAccSucc
   * @generated
   */
  EClass getOpAccSucc();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.OpAccSucc#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see org.xtext.example.mydsl.myDsl.OpAccSucc#getOp()
   * @see #getOpAccSucc()
   * @generated
   */
  EAttribute getOpAccSucc_Op();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Not <em>Not</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Not</em>'.
   * @see org.xtext.example.mydsl.myDsl.Not
   * @generated
   */
  EClass getNot();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Not#getExpr <em>Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expr</em>'.
   * @see org.xtext.example.mydsl.myDsl.Not#getExpr()
   * @see #getNot()
   * @generated
   */
  EReference getNot_Expr();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Not#getNot <em>Not</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Not</em>'.
   * @see org.xtext.example.mydsl.myDsl.Not#getNot()
   * @see #getNot()
   * @generated
   */
  EAttribute getNot_Not();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.OpConstructeur <em>Op Constructeur</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Op Constructeur</em>'.
   * @see org.xtext.example.mydsl.myDsl.OpConstructeur
   * @generated
   */
  EClass getOpConstructeur();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.OpConstructeur#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see org.xtext.example.mydsl.myDsl.OpConstructeur#getOp()
   * @see #getOpConstructeur()
   * @generated
   */
  EAttribute getOpConstructeur_Op();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.COMPARATEUR <em>COMPARATEUR</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>COMPARATEUR</em>'.
   * @see org.xtext.example.mydsl.myDsl.COMPARATEUR
   * @generated
   */
  EClass getCOMPARATEUR();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.COMPARATEUR#getComparateur <em>Comparateur</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Comparateur</em>'.
   * @see org.xtext.example.mydsl.myDsl.COMPARATEUR#getComparateur()
   * @see #getCOMPARATEUR()
   * @generated
   */
  EAttribute getCOMPARATEUR_Comparateur();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyDslFactory getMyDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ProgramImpl <em>Program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ProgramImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getProgram()
     * @generated
     */
    EClass PROGRAM = eINSTANCE.getProgram();

    /**
     * The meta object literal for the '<em><b>Fonctions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAM__FONCTIONS = eINSTANCE.getProgram_Fonctions();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.FonctionImpl <em>Fonction</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.FonctionImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getFonction()
     * @generated
     */
    EClass FONCTION = eINSTANCE.getFonction();

    /**
     * The meta object literal for the '<em><b>Nom</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FONCTION__NOM = eINSTANCE.getFonction_Nom();

    /**
     * The meta object literal for the '<em><b>In</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FONCTION__IN = eINSTANCE.getFonction_In();

    /**
     * The meta object literal for the '<em><b>Commandes</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FONCTION__COMMANDES = eINSTANCE.getFonction_Commandes();

    /**
     * The meta object literal for the '<em><b>Out</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FONCTION__OUT = eINSTANCE.getFonction_Out();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.CommandesImpl <em>Commandes</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.CommandesImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getCommandes()
     * @generated
     */
    EClass COMMANDES = eINSTANCE.getCommandes();

    /**
     * The meta object literal for the '<em><b>Commande</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMMANDES__COMMANDE = eINSTANCE.getCommandes_Commande();

    /**
     * The meta object literal for the '<em><b>Commandes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMMANDES__COMMANDES = eINSTANCE.getCommandes_Commandes();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.CommandeImpl <em>Commande</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.CommandeImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getCommande()
     * @generated
     */
    EClass COMMANDE = eINSTANCE.getCommande();

    /**
     * The meta object literal for the '<em><b>Commande</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMMANDE__COMMANDE = eINSTANCE.getCommande_Commande();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.AffectationImpl <em>Affectation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.AffectationImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getAffectation()
     * @generated
     */
    EClass AFFECTATION = eINSTANCE.getAffectation();

    /**
     * The meta object literal for the '<em><b>Variable</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AFFECTATION__VARIABLE = eINSTANCE.getAffectation_Variable();

    /**
     * The meta object literal for the '<em><b>Elm</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AFFECTATION__ELM = eINSTANCE.getAffectation_Elm();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.IfImpl <em>If</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.IfImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getIf()
     * @generated
     */
    EClass IF = eINSTANCE.getIf();

    /**
     * The meta object literal for the '<em><b>Cond</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF__COND = eINSTANCE.getIf_Cond();

    /**
     * The meta object literal for the '<em><b>Cmds If</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF__CMDS_IF = eINSTANCE.getIf_CmdsIf();

    /**
     * The meta object literal for the '<em><b>Cmds Else</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF__CMDS_ELSE = eINSTANCE.getIf_CmdsElse();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.WhileImpl <em>While</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.WhileImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getWhile()
     * @generated
     */
    EClass WHILE = eINSTANCE.getWhile();

    /**
     * The meta object literal for the '<em><b>Cond</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WHILE__COND = eINSTANCE.getWhile_Cond();

    /**
     * The meta object literal for the '<em><b>Cmds Wh</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WHILE__CMDS_WH = eINSTANCE.getWhile_CmdsWh();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ForImpl <em>For</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ForImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getFor()
     * @generated
     */
    EClass FOR = eINSTANCE.getFor();

    /**
     * The meta object literal for the '<em><b>Cond</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FOR__COND = eINSTANCE.getFor_Cond();

    /**
     * The meta object literal for the '<em><b>Cmds For</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FOR__CMDS_FOR = eINSTANCE.getFor_CmdsFor();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ForEachImpl <em>For Each</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ForEachImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getForEach()
     * @generated
     */
    EClass FOR_EACH = eINSTANCE.getForEach();

    /**
     * The meta object literal for the '<em><b>Elem</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FOR_EACH__ELEM = eINSTANCE.getForEach_Elem();

    /**
     * The meta object literal for the '<em><b>Ensemble</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FOR_EACH__ENSEMBLE = eINSTANCE.getForEach_Ensemble();

    /**
     * The meta object literal for the '<em><b>Cmds For</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FOR_EACH__CMDS_FOR = eINSTANCE.getForEach_CmdsFor();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.NopImpl <em>Nop</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.NopImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getNop()
     * @generated
     */
    EClass NOP = eINSTANCE.getNop();

    /**
     * The meta object literal for the '<em><b>Nop</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NOP__NOP = eINSTANCE.getNop_Nop();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ExpressionImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '<em><b>Cond</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION__COND = eINSTANCE.getExpression_Cond();

    /**
     * The meta object literal for the '<em><b>Exprs</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION__EXPRS = eINSTANCE.getExpression_Exprs();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ExprSimpleImpl <em>Expr Simple</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ExprSimpleImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getExprSimple()
     * @generated
     */
    EClass EXPR_SIMPLE = eINSTANCE.getExprSimple();

    /**
     * The meta object literal for the '<em><b>Nil</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPR_SIMPLE__NIL = eINSTANCE.getExprSimple_Nil();

    /**
     * The meta object literal for the '<em><b>Variable</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPR_SIMPLE__VARIABLE = eINSTANCE.getExprSimple_Variable();

    /**
     * The meta object literal for the '<em><b>Abin</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPR_SIMPLE__ABIN = eINSTANCE.getExprSimple_Abin();

    /**
     * The meta object literal for the '<em><b>Symb</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPR_SIMPLE__SYMB = eINSTANCE.getExprSimple_Symb();

    /**
     * The meta object literal for the '<em><b>Accsucc</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPR_SIMPLE__ACCSUCC = eINSTANCE.getExprSimple_Accsucc();

    /**
     * The meta object literal for the '<em><b>Elem Simple</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPR_SIMPLE__ELEM_SIMPLE = eINSTANCE.getExprSimple_ElemSimple();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.VariableImpl <em>Variable</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.VariableImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getVariable()
     * @generated
     */
    EClass VARIABLE = eINSTANCE.getVariable();

    /**
     * The meta object literal for the '<em><b>Variable</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE__VARIABLE = eINSTANCE.getVariable_Variable();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.LexprImpl <em>Lexpr</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.LexprImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getLexpr()
     * @generated
     */
    EClass LEXPR = eINSTANCE.getLexpr();

    /**
     * The meta object literal for the '<em><b>E1</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LEXPR__E1 = eINSTANCE.getLexpr_E1();

    /**
     * The meta object literal for the '<em><b>Lexpr</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LEXPR__LEXPR = eINSTANCE.getLexpr_Lexpr();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ElemSimpleImpl <em>Elem Simple</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ElemSimpleImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getElemSimple()
     * @generated
     */
    EClass ELEM_SIMPLE = eINSTANCE.getElemSimple();

    /**
     * The meta object literal for the '<em><b>Symb</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ELEM_SIMPLE__SYMB = eINSTANCE.getElemSimple_Symb();

    /**
     * The meta object literal for the '<em><b>Lexpr</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ELEM_SIMPLE__LEXPR = eINSTANCE.getElemSimple_Lexpr();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ConditionImpl <em>Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ConditionImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getCondition()
     * @generated
     */
    EClass CONDITION = eINSTANCE.getCondition();

    /**
     * The meta object literal for the '<em><b>E1</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONDITION__E1 = eINSTANCE.getCondition_E1();

    /**
     * The meta object literal for the '<em><b>Comp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONDITION__COMP = eINSTANCE.getCondition_Comp();

    /**
     * The meta object literal for the '<em><b>E2</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONDITION__E2 = eINSTANCE.getCondition_E2();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.ABinImpl <em>ABin</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.ABinImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getABin()
     * @generated
     */
    EClass ABIN = eINSTANCE.getABin();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ABIN__OP = eINSTANCE.getABin_Op();

    /**
     * The meta object literal for the '<em><b>E1</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ABIN__E1 = eINSTANCE.getABin_E1();

    /**
     * The meta object literal for the '<em><b>E2</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ABIN__E2 = eINSTANCE.getABin_E2();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.AccSuccImpl <em>Acc Succ</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.AccSuccImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getAccSucc()
     * @generated
     */
    EClass ACC_SUCC = eINSTANCE.getAccSucc();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACC_SUCC__OP = eINSTANCE.getAccSucc_Op();

    /**
     * The meta object literal for the '<em><b>Expr</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACC_SUCC__EXPR = eINSTANCE.getAccSucc_Expr();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.OutputImpl <em>Output</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.OutputImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getOutput()
     * @generated
     */
    EClass OUTPUT = eINSTANCE.getOutput();

    /**
     * The meta object literal for the '<em><b>Out</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OUTPUT__OUT = eINSTANCE.getOutput_Out();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.InputImpl <em>Input</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.InputImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getInput()
     * @generated
     */
    EClass INPUT = eINSTANCE.getInput();

    /**
     * The meta object literal for the '<em><b>In</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INPUT__IN = eINSTANCE.getInput_In();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.NillImpl <em>Nill</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.NillImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getNill()
     * @generated
     */
    EClass NILL = eINSTANCE.getNill();

    /**
     * The meta object literal for the '<em><b>Nil</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NILL__NIL = eINSTANCE.getNill_Nil();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.OpAccSuccImpl <em>Op Acc Succ</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.OpAccSuccImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getOpAccSucc()
     * @generated
     */
    EClass OP_ACC_SUCC = eINSTANCE.getOpAccSucc();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OP_ACC_SUCC__OP = eINSTANCE.getOpAccSucc_Op();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.NotImpl <em>Not</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.NotImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getNot()
     * @generated
     */
    EClass NOT = eINSTANCE.getNot();

    /**
     * The meta object literal for the '<em><b>Expr</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NOT__EXPR = eINSTANCE.getNot_Expr();

    /**
     * The meta object literal for the '<em><b>Not</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NOT__NOT = eINSTANCE.getNot_Not();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.OpConstructeurImpl <em>Op Constructeur</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.OpConstructeurImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getOpConstructeur()
     * @generated
     */
    EClass OP_CONSTRUCTEUR = eINSTANCE.getOpConstructeur();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OP_CONSTRUCTEUR__OP = eINSTANCE.getOpConstructeur_Op();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.COMPARATEURImpl <em>COMPARATEUR</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.COMPARATEURImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getCOMPARATEUR()
     * @generated
     */
    EClass COMPARATEUR = eINSTANCE.getCOMPARATEUR();

    /**
     * The meta object literal for the '<em><b>Comparateur</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPARATEUR__COMPARATEUR = eINSTANCE.getCOMPARATEUR_Comparateur();

  }

} //MyDslPackage
